[versions]
    minecraft = "1.20.4"
    quilt_mappings = "1.20.4+build.3"
    fabric-loader = "0.15.10"
    fabric-api = "0.97.0+1.20.4"
    parchment = "2023.09.03"
[libraries]
    minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
    fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader"}